package com.example.data.export

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.data.model.TripEntity
import com.example.data.repository.UserProfile
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

enum class ExportFormat {
  PDF, CSV
}

enum class ExportScope {
  ALL, CURRENT_MONTH, FILTERED
}

object ExportManager {

  private const val PAGE_WIDTH = 595
  private const val PAGE_HEIGHT = 842
  private const val MARGIN = 36f

  /**
   * Generates a CSV file containing the trip logs and financial totals.
   */
  fun generateCsvReport(
    context: Context,
    trips: List<TripEntity>,
    profile: UserProfile
  ): File {
    val exportDir = File(context.cacheDir, "exports").apply { mkdirs() }
    val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())
    val file = File(exportDir, "CarHisab_Trips_$timestamp.csv")

    val totalRent = trips.sumOf { it.rent }
    val totalGratuity = trips.sumOf { it.gratuity }
    val totalMaintenance = trips.sumOf { it.maintenanceCost }
    val totalIncome = trips.sumOf { it.income }
    val totalProfit = trips.sumOf { it.profit }
    val totalKm = trips.sumOf { it.kmDriven }

    val dateFormatted = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.US).format(Date())

    val sb = java.lang.StringBuilder()
    // UTF-8 BOM for Microsoft Excel compatibility
    sb.append('\uFEFF')

    // Header metadata comments
    sb.append("# CAR HISAB — TRIP ACCOUNTING REPORT\n")
    sb.append("# Driver: ${escapeCsv(profile.driverName)}\n")
    sb.append("# Vehicle: ${escapeCsv(profile.carName)} (${escapeCsv(profile.carModel)})\n")
    sb.append("# Reg Plate: ${escapeCsv(profile.carNumber)}\n")
    sb.append("# Phone: ${escapeCsv(profile.driverPhone)}\n")
    sb.append("# Export Date: ${escapeCsv(dateFormatted)}\n")
    sb.append("# Total Records: ${trips.size}\n#\n")

    // CSV Column headers
    sb.append("Trip ID,Date,Destination / Place,Distance (KM),Rent (BDT),Trip Expense (BDT),Maintenance Cost (BDT),Net Income (BDT),Net Profit (BDT),Notes\n")

    // Rows
    for (trip in trips) {
      sb.append(trip.id).append(",")
      sb.append(escapeCsv(trip.dateString)).append(",")
      sb.append(escapeCsv(trip.place)).append(",")
      sb.append(String.format(Locale.US, "%.1f", trip.kmDriven)).append(",")
      sb.append(String.format(Locale.US, "%.2f", trip.rent)).append(",")
      sb.append(String.format(Locale.US, "%.2f", trip.gratuity)).append(",")
      sb.append(String.format(Locale.US, "%.2f", trip.maintenanceCost)).append(",")
      sb.append(String.format(Locale.US, "%.2f", trip.income)).append(",")
      sb.append(String.format(Locale.US, "%.2f", trip.profit)).append(",")
      sb.append(escapeCsv(trip.description))
      sb.append("\n")
    }

    // Summary totals row
    sb.append("\n")
    sb.append("TOTAL SUMMARY,,")
    sb.append(String.format(Locale.US, "%.1f", totalKm)).append(" KM,")
    sb.append(String.format(Locale.US, "%.2f", totalRent)).append(",")
    sb.append(String.format(Locale.US, "%.2f", totalGratuity)).append(",")
    sb.append(String.format(Locale.US, "%.2f", totalMaintenance)).append(",")
    sb.append(String.format(Locale.US, "%.2f", totalIncome)).append(",")
    sb.append(String.format(Locale.US, "%.2f", totalProfit)).append(",")
    sb.append("Generated by Car Hisab - MMRK Innovations\n")

    FileOutputStream(file).use { out ->
      out.write(sb.toString().toByteArray(Charsets.UTF_8))
    }

    return file
  }

  private fun escapeCsv(value: String): String {
    val clean = value.replace("\r", " ").replace("\n", " ")
    return if (clean.contains(",") || clean.contains("\"") || clean.contains(";")) {
      "\"" + clean.replace("\"", "\"\"") + "\""
    } else {
      clean
    }
  }

  /**
   * Generates a multi-page PDF document statement formatted for accounting and tax records.
   */
  fun generatePdfReport(
    context: Context,
    trips: List<TripEntity>,
    profile: UserProfile,
    title: String = "Trip Accounting Statement"
  ): File {
    val exportDir = File(context.cacheDir, "exports").apply { mkdirs() }
    val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())
    val file = File(exportDir, "CarHisab_Report_$timestamp.pdf")

    val pdfDocument = PdfDocument()

    // Paints
    val paintText = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      color = Color.rgb(30, 41, 59) // slate 800
      textSize = 9f
    }
    val paintBold = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      color = Color.rgb(15, 23, 42) // slate 900
      typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
      textSize = 9f
    }
    val paintFill = Paint(Paint.ANTI_ALIAS_FLAG)
    val paintLine = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      strokeWidth = 0.75f
      color = Color.rgb(226, 232, 240) // slate 200
    }

    val totalRent = trips.sumOf { it.rent }
    val totalGratuity = trips.sumOf { it.gratuity }
    val totalMaintenance = trips.sumOf { it.maintenanceCost }
    val totalIncome = trips.sumOf { it.income }
    val totalProfit = trips.sumOf { it.profit }
    val totalKm = trips.sumOf { it.kmDriven }
    val exportDateStr = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.US).format(Date())

    // Estimate rows per page
    // Page 1 has header (banner + profile + kpi summary) taking ~220pt.
    // Usable table area on Page 1: ~560pt. At 20pt/row, ~28 rows.
    // Subsequent pages have compact header ~70pt, table area ~700pt, ~35 rows.
    val rowsFirstPage = 22
    val rowsPerPage = 32

    var tripIndex = 0
    var pageNumber = 1
    val totalPages = calculateTotalPages(trips.size, rowsFirstPage, rowsPerPage)

    while (tripIndex < trips.size || pageNumber == 1) {
      val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
      val page = pdfDocument.startPage(pageInfo)
      val canvas = page.canvas

      var currentY: Float

      if (pageNumber == 1) {
        // --- PAGE 1 FULL HEADER ---
        // Top Emerald Banner
        paintFill.color = Color.rgb(15, 118, 110) // #0F766E
        canvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), 64f, paintFill)

        // Title
        paintBold.color = Color.WHITE
        paintBold.textSize = 15f
        canvas.drawText("CAR HISAB — $title", MARGIN, 28f, paintBold)

        paintText.color = Color.rgb(204, 251, 241) // teal 100
        paintText.textSize = 8.5f
        canvas.drawText("MMRK INNOVATIONS • SMART DRIVER FINANCIAL & TRIP ACCOUNTING", MARGIN, 46f, paintText)

        val dateLabel = "DATE: $exportDateStr"
        val dateWidth = paintText.measureText(dateLabel)
        canvas.drawText(dateLabel, PAGE_WIDTH - MARGIN - dateWidth, 46f, paintText)

        // Profile & Vehicle Card
        currentY = 76f
        paintFill.color = Color.rgb(248, 250, 252) // slate 50
        val profileRect = RectF(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY + 54f)
        canvas.drawRoundRect(profileRect, 6f, 6f, paintFill)
        paintLine.color = Color.rgb(203, 213, 225)
        canvas.drawRoundRect(profileRect, 6f, 6f, paintLine)

        paintBold.color = Color.rgb(15, 23, 42)
        paintBold.textSize = 9.5f
        canvas.drawText("DRIVER & VEHICLE SPECIFICATIONS", MARGIN + 10f, currentY + 16f, paintBold)

        paintText.color = Color.rgb(71, 85, 105)
        paintText.textSize = 8.5f
        canvas.drawText("Driver: ${profile.driverName}", MARGIN + 10f, currentY + 32f, paintText)
        canvas.drawText("Phone: ${profile.driverPhone}", MARGIN + 10f, currentY + 45f, paintText)

        canvas.drawText("Vehicle: ${profile.carName} (${profile.carModel})", MARGIN + 180f, currentY + 32f, paintText)
        canvas.drawText("Reg Plate: ${profile.carNumber}", MARGIN + 180f, currentY + 45f, paintText)

        canvas.drawText("Trips Logged: ${trips.size}", MARGIN + 370f, currentY + 32f, paintText)
        canvas.drawText("Total Dist: ${String.format(Locale.US, "%.1f", totalKm)} KM", MARGIN + 370f, currentY + 45f, paintText)

        // KPI Metric Cards (4 cards across width)
        currentY = 138f
        val cardWidth = (PAGE_WIDTH - 2 * MARGIN - 3 * 8f) / 4f
        val cardHeight = 44f

        drawKpiCard(canvas, MARGIN, currentY, cardWidth, cardHeight, "GROSS RENT", "৳" + formatAmount(totalRent), Color.rgb(30, 41, 59))
        drawKpiCard(canvas, MARGIN + cardWidth + 8f, currentY, cardWidth, cardHeight, "TRIP EXPENSE", "৳" + formatAmount(totalGratuity), Color.rgb(100, 116, 139))
        drawKpiCard(canvas, MARGIN + (cardWidth + 8f) * 2, currentY, cardWidth, cardHeight, "MAINTENANCE", "৳" + formatAmount(totalMaintenance), Color.rgb(225, 29, 72))

        val profitColor = if (totalProfit >= 0) Color.rgb(16, 185, 129) else Color.rgb(239, 68, 68)
        drawKpiCard(canvas, MARGIN + (cardWidth + 8f) * 3, currentY, cardWidth, cardHeight, "NET PROFIT", "৳" + formatAmount(totalProfit), profitColor, isHighlight = true)

        currentY = 194f
      } else {
        // Compact continuation header for pages > 1
        paintFill.color = Color.rgb(15, 118, 110)
        canvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), 34f, paintFill)

        paintBold.color = Color.WHITE
        paintBold.textSize = 10f
        canvas.drawText("CAR HISAB — $title (Continued)", MARGIN, 21f, paintBold)

        paintText.color = Color.rgb(204, 251, 241)
        paintText.textSize = 8f
        val pageLabel = "Page $pageNumber of $totalPages"
        canvas.drawText(pageLabel, PAGE_WIDTH - MARGIN - paintText.measureText(pageLabel), 21f, paintText)

        currentY = 44f
      }

      // Draw Table Header
      currentY = drawTableHeader(canvas, currentY)

      // Rows on this page
      val maxRowsThisPage = if (pageNumber == 1) rowsFirstPage else rowsPerPage
      var rowsDrawn = 0

      while (tripIndex < trips.size && rowsDrawn < maxRowsThisPage) {
        val trip = trips[tripIndex]
        currentY = drawTableRow(canvas, currentY, tripIndex + 1, trip)
        tripIndex++
        rowsDrawn++
      }

      // If all trips drawn, draw TOTAL row
      if (tripIndex >= trips.size) {
        currentY = drawTableTotalRow(
          canvas = canvas,
          y = currentY,
          totalKm = totalKm,
          totalRent = totalRent,
          totalGratuity = totalGratuity,
          totalMaintenance = totalMaintenance,
          totalProfit = totalProfit
        )
      }

      // Draw Footer
      drawFooter(canvas, pageNumber, totalPages)

      pdfDocument.finishPage(page)
      pageNumber++

      if (tripIndex >= trips.size) break
    }

    FileOutputStream(file).use { out ->
      pdfDocument.writeTo(out)
    }
    pdfDocument.close()

    return file
  }

  private fun calculateTotalPages(totalTrips: Int, firstPageRows: Int, laterPageRows: Int): Int {
    if (totalTrips <= firstPageRows) return 1
    val remaining = totalTrips - firstPageRows
    return 1 + kotlin.math.ceil(remaining.toDouble() / laterPageRows).toInt()
  }

  private fun drawKpiCard(
    canvas: Canvas,
    x: Float,
    y: Float,
    w: Float,
    h: Float,
    title: String,
    value: String,
    valueColor: Int,
    isHighlight: Boolean = false
  ) {
    val bgPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      color = if (isHighlight) Color.rgb(240, 253, 244) else Color.rgb(248, 250, 252)
    }
    val borderPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      style = Paint.Style.STROKE
      strokeWidth = 0.75f
      color = if (isHighlight) Color.rgb(187, 247, 208) else Color.rgb(226, 232, 240)
    }
    val titlePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      color = Color.rgb(100, 116, 139)
      textSize = 7f
      typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
    }
    val valPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      color = valueColor
      textSize = 10f
      typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
    }

    val rect = RectF(x, y, x + w, y + h)
    canvas.drawRoundRect(rect, 4f, 4f, bgPaint)
    canvas.drawRoundRect(rect, 4f, 4f, borderPaint)

    canvas.drawText(title, x + 6f, y + 14f, titlePaint)
    canvas.drawText(value, x + 6f, y + 32f, valPaint)
  }

  private fun drawTableHeader(canvas: Canvas, y: Float): Float {
    val headerHeight = 20f
    val bgPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      color = Color.rgb(226, 232, 240) // slate 200
    }
    canvas.drawRect(MARGIN, y, PAGE_WIDTH - MARGIN, y + headerHeight, bgPaint)

    val paint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      color = Color.rgb(30, 41, 59)
      textSize = 7.5f
      typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
    }

    val textY = y + 13.5f
    canvas.drawText("#", MARGIN + 4f, textY, paint)
    canvas.drawText("DATE", MARGIN + 22f, textY, paint)
    canvas.drawText("DESTINATION / ROUTE", MARGIN + 90f, textY, paint)
    drawRightAlignedText(canvas, "KM", MARGIN + 276f, textY, paint)
    drawRightAlignedText(canvas, "RENT (৳)", MARGIN + 338f, textY, paint)
    drawRightAlignedText(canvas, "TRIP EXP (৳)", MARGIN + 396f, textY, paint)
    drawRightAlignedText(canvas, "MAINT (৳)", MARGIN + 456f, textY, paint)
    drawRightAlignedText(canvas, "PROFIT (৳)", PAGE_WIDTH - MARGIN - 4f, textY, paint)

    return y + headerHeight
  }

  private fun drawTableRow(canvas: Canvas, y: Float, index: Int, trip: TripEntity): Float {
    val rowHeight = 18f
    val bgPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      color = if (index % 2 == 0) Color.rgb(248, 250, 252) else Color.WHITE
    }
    canvas.drawRect(MARGIN, y, PAGE_WIDTH - MARGIN, y + rowHeight, bgPaint)

    // Border line under row
    val linePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      strokeWidth = 0.5f
      color = Color.rgb(241, 245, 249)
    }
    canvas.drawLine(MARGIN, y + rowHeight, PAGE_WIDTH - MARGIN, y + rowHeight, linePaint)

    val textPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      color = Color.rgb(51, 65, 85)
      textSize = 7.5f
    }
    val boldPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
      textSize = 7.5f
    }

    val textY = y + 12.5f

    // # Index
    canvas.drawText(index.toString(), MARGIN + 4f, textY, textPaint)

    // Date
    canvas.drawText(trip.dateString, MARGIN + 22f, textY, textPaint)

    // Destination / Place (truncate if too long)
    val placeTruncated = truncateString(trip.place, 26)
    canvas.drawText(placeTruncated, MARGIN + 90f, textY, boldPaint.apply { color = Color.rgb(15, 23, 42) })

    // KM
    val kmText = if (trip.kmDriven > 0) String.format(Locale.US, "%.1f", trip.kmDriven) else "-"
    drawRightAlignedText(canvas, kmText, MARGIN + 276f, textY, textPaint)

    // Rent
    drawRightAlignedText(canvas, formatAmount(trip.rent), MARGIN + 338f, textY, textPaint)

    // Gratuity
    drawRightAlignedText(canvas, formatAmount(trip.gratuity), MARGIN + 396f, textY, textPaint)

    // Maintenance
    drawRightAlignedText(canvas, formatAmount(trip.maintenanceCost), MARGIN + 456f, textY, textPaint)

    // Profit
    val isProfit = trip.profit >= 0
    val profitColor = if (isProfit) Color.rgb(16, 185, 129) else Color.rgb(239, 68, 68)
    boldPaint.color = profitColor
    drawRightAlignedText(canvas, formatAmount(trip.profit), PAGE_WIDTH - MARGIN - 4f, textY, boldPaint)

    return y + rowHeight
  }

  private fun drawTableTotalRow(
    canvas: Canvas,
    y: Float,
    totalKm: Double,
    totalRent: Double,
    totalGratuity: Double,
    totalMaintenance: Double,
    totalProfit: Double
  ): Float {
    val rowHeight = 22f
    val bgPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      color = Color.rgb(241, 245, 249) // slate 100
    }
    canvas.drawRect(MARGIN, y, PAGE_WIDTH - MARGIN, y + rowHeight, bgPaint)

    val topBorderPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      strokeWidth = 1f
      color = Color.rgb(148, 163, 184)
    }
    canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, topBorderPaint)
    canvas.drawLine(MARGIN, y + rowHeight, PAGE_WIDTH - MARGIN, y + rowHeight, topBorderPaint)

    val boldPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
      color = Color.rgb(15, 23, 42)
      textSize = 8f
    }

    val textY = y + 14.5f
    canvas.drawText("TOTAL", MARGIN + 4f, textY, boldPaint)

    // KM Total
    drawRightAlignedText(canvas, String.format(Locale.US, "%.1f", totalKm), MARGIN + 276f, textY, boldPaint)

    // Rent Total
    drawRightAlignedText(canvas, "৳" + formatAmount(totalRent), MARGIN + 338f, textY, boldPaint)

    // Gratuity Total
    drawRightAlignedText(canvas, "৳" + formatAmount(totalGratuity), MARGIN + 396f, textY, boldPaint)

    // Maintenance Total
    drawRightAlignedText(canvas, "৳" + formatAmount(totalMaintenance), MARGIN + 456f, textY, boldPaint)

    // Profit Total
    val profitColor = if (totalProfit >= 0) Color.rgb(16, 185, 129) else Color.rgb(239, 68, 68)
    boldPaint.color = profitColor
    drawRightAlignedText(canvas, "৳" + formatAmount(totalProfit), PAGE_WIDTH - MARGIN - 4f, textY, boldPaint)

    return y + rowHeight
  }

  private fun drawFooter(canvas: Canvas, currentPage: Int, totalPages: Int) {
    val y = PAGE_HEIGHT - 26f
    val linePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      strokeWidth = 0.5f
      color = Color.rgb(203, 213, 225)
    }
    canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, linePaint)

    val textPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
      color = Color.rgb(148, 163, 184)
      textSize = 7.5f
    }

    val footerLeft = "Car Hisab by MMRK Innovations • Driver Accounting Records"
    canvas.drawText(footerLeft, MARGIN, y + 14f, textPaint)

    val footerRight = "Page $currentPage of $totalPages"
    val rightWidth = textPaint.measureText(footerRight)
    canvas.drawText(footerRight, PAGE_WIDTH - MARGIN - rightWidth, y + 14f, textPaint)
  }

  private fun drawRightAlignedText(canvas: Canvas, text: String, rightX: Float, y: Float, paint: Paint) {
    val width = paint.measureText(text)
    canvas.drawText(text, rightX - width, y, paint)
  }

  private fun formatAmount(value: Double): String {
    return String.format(Locale.US, "%,.0f", value)
  }

  private fun truncateString(text: String, maxLen: Int): String {
    return if (text.length > maxLen) {
      text.take(maxLen - 1) + "…"
    } else {
      text
    }
  }

  /**
   * Fires an Android ACTION_SEND intent with FileProvider URI to share or save the file.
   */
  fun shareExportedFile(
    context: Context,
    file: File,
    mimeType: String,
    title: String,
    summaryMessage: String
  ) {
    try {
      val authority = "${context.packageName}.fileprovider"
      val uri: Uri = FileProvider.getUriForFile(context, authority, file)

      val intent = Intent(Intent.ACTION_SEND).apply {
        type = mimeType
        putExtra(Intent.EXTRA_STREAM, uri)
        putExtra(Intent.EXTRA_SUBJECT, title)
        putExtra(Intent.EXTRA_TEXT, summaryMessage)
        addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
      }

      val chooser = Intent.createChooser(intent, title).apply {
        addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
      }
      context.startActivity(chooser)
    } catch (e: Exception) {
      Toast.makeText(context, "Error exporting file: ${e.localizedMessage}", Toast.LENGTH_LONG).show()
    }
  }
}
